
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        cd mcp_server
        docker-compose build

    - name: Run tests
      run: |
        cd mcp_server
        docker-compose run --rm tester

    - name: Run linters
      run: |
        cd mcp_server
        docker-compose run --rm server bash -c "flake8 app && black --check app"
