name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Bring up services
      run: |
        cd mcp_server
        docker compose up -d

    - name: Run tests
      run: |
        cd mcp_server
        docker compose run --rm tester

    - name: Display Python Analyzer logs on failure
      if: failure()
      run: |
        cd mcp_server
        docker compose logs python_analyzer

    - name: Run linters
      run: |
        cd mcp_server
        docker compose run --rm server bash -c "flake8 app && black --check app"